### ISSUE TITLE
setHorizontal

### ISSUE THREAD

**Issue by rifton007** [Holt59/cakephp-bootstrap3-helpers#11]
Hi all, thanks for your help.

The setHorizontal for formHelper, is available for CakePHP 2.x ?
echo $this->Form->setHorizontal (true) ;

Thanks,

**Comment by Holt59** [comment]
Hi,

The `setHorizontal` method is not available but:

```php
$this->Form->horizontal = true ;
$this->Form->horizontal = false ;
```

...should be sufficient for the 2.x helpers.

**Comment by rifton007** [comment]
Thanks, but it does not work for me.

![image](https://cloud.githubusercontent.com/assets/2601347/11420622/918551a6-942f-11e5-9a16-c0b2d97f9283.png)


```php
$this->Form->horizontal = true;
echo $this->Form->input('username', array('label' => 'Nom utilisateur', 'value' => 'test'));
echo $this->Form->input('mail', array('label' => 'Adresse utilisateur', 'value' => 'test@weddingplaza.com'));
echo $this->Form->input('password', array('value' => '00'));
echo $this->Form->input('password', array('value' => '00'));
```

**Comment by Holt59** [comment]
You cannot start with a non-horizontal form and add horizontal inputs because horizontal inputs do not work if the form does not have the `form-horizontal` class. Try starting with a horizontal form and removing the horizontal property when you need it.

**Comment by rifton007** [comment]
Thanks Holt59.
I wish you much success in your work.
