### ISSUE TITLE
Do not stylized input of type "password"

### ISSUE THREAD

**Issue by rifton007** [Holt59/cakephp-bootstrap3-helpers#12]
Hello and Happy New Year too,

Is someone the same problem as me?
The input of type "password" are not stylize.

Thank you,

**Comment by Holt59** [comment]
Are you doing the following by chance?

```php
echo $this->Form->password();
```

If so, then you should switch to:

```php
echo $this->Form->input('...', [
    'type' => 'password'
]);
```

**Comment by rifton007** [comment]
This is solved for me, thank you Holt59.
```php
echo $this->Form->input('...', [
    'type' => 'password'
]);
```
