### ISSUE TITLE
Default label for checkboxes does not show up

### ISSUE THREAD

**Issue by MarkusBauer** [Holt59/cakephp-bootstrap3-helpers#16]
When creating a checkbox without setting a label explicitly, no text is shown. With the default `FormHelper`, the field's name is used. Example: 

```
<?= $this->Form->input('avaiable', array('type' => 'checkbox')) ?>
```

The cause is located in `BootstrapFormHelper::label()`, which does not handle the case `$text === null` for checkboxes (as it does not use the parent's method). I would propose a fix like this (replacing line 173 to 175): 

```
if ($this->currentInputType == 'checkbox') {
    if ($text === null) { // this case is new - code copied from cake's FormHelper
        if (strpos($fieldName, '.') !== false) {
            $fieldElements = explode('.', $fieldName);
            $text = array_pop($fieldElements);
        } else {
            $text = $fieldName;
        }
        if (substr($text, -3) === '_id') {
            $text = substr($text, 0, -3);
        }
        $text = __(Inflector::humanize(Inflector::underscore($text)));
    }
    return $text ;
}
```

Best regards
Markus Bauer

**Comment by Holt59** [comment]
Should be fixed by 6baffd6caa0930ccadb315ce51298a0ce11cb6be. I did not test it though. Feel free to directly open a pull-request next time if you feel something should be updated, I am not actively working on this repository anymore.
