### ISSUE TITLE
Wrong layout for radio an select

### ISSUE THREAD

**Issue by nandosb** [Holt59/cakephp-bootstrap3-helpers#8]
According to CakePHP Form Helper documentation, you should create radio buttons and selects with the following code:

//Radio Button
$options = array('M' => 'Male', 'F' => 'Female');
$attributes = array('legend' => false);
echo $this->Form->radio('gender', $options, $attributes);

//Select
$options = array('M' => 'Male', 'F' => 'Female');
echo $this->Form->select('gender', $options);

The current output, for horizontal form, is in the attachment
![cakephp2-bootstra3-helper](https://cloud.githubusercontent.com/assets/3045567/6097467/31de7074-af9d-11e4-9029-d01c2e205b13.png)

And for non-horizontal form, the output is
![cakephp2-bootstra3-helper2](https://cloud.githubusercontent.com/assets/3045567/6097474/b3145fa0-af9d-11e4-91e2-a21ecf14f86c.png)

**Comment by Holt59** [comment]
What I understand from the FormHelper documentation, and the way I want my plugin to work is the following: 
- If you want to have bootstrap layout (i.e., the Helper wrapping your inputs), use the `input` method
- If you want raw input / select / etc., use the direct methods (select, input, radio, etc.)

This is the way the default CakePHP FormHelper works: If you use the default `input` method, the helper wraps the inputs elements into `div`, if you use the direct methods, there is no "wrapping".

If you want Bootstrap layout, use the following codes:
```
//Radio Button
$options = array('M' => 'Male', 'F' => 'Female');
echo $this->Form->input('gender', array('type' => 'radio', 'options' => $options, 'legend' => FALSE));

//Select
$options = array('M' => 'Male', 'F' => 'Female');
echo $this->Form->input('gender', array( 'options' => $options));
```

**Comment by nandosb** [comment]
Thanks Holt59. I understand your point.
However, I still thinking there are a strange behavior on inline radio button.

If I write
//Radio Button
$options = array('M' => 'Male', 'F' => 'Female', 'T' => 'Trans');
echo $this->Form->input('gender', array('type' => 'radio', 'options' => $options, 'legend' => false, 'inline'=> TRUE);

The first radio button is above the others. Please, see the picture below
![cakephp2-bootstra3-helper3](https://cloud.githubusercontent.com/assets/3045567/6099904/72daba10-afe3-11e4-8770-f34acf0203c1.png)

If you look the firstone, it has a different class: radio vs. radio-inline in the other inputs
Am I missing some parameter??

**Comment by Holt59** [comment]
No you're not, there were some bugs. This should be fixed with the latest commit.

**Comment by nandosb** [comment]
Thank Holt59, It´s working OK now
